version: "3.8"
services:
  redis-node-0:
    image: redis:5.0.9
    container_name: redis-node-0
    env_file: .env
    command: /bin/bash -c 'redis-server /etc/redis/redis.conf --port 7000 --cluster-announce-ip ${IP}'
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-0/data:/data
      #- ./redis-cluster/nodes/node-0/log:/log
    ports:
      - 7000:7000
      - 17000:17000
    networks:
      redisNet:
        ipv4_address: 172.28.0.2
  redis-node-1:
    image: redis:5.0.9
    container_name: redis-node-1
    env_file: .env
    command: /bin/bash -c 'redis-server /etc/redis/redis.conf --port 7001 --cluster-announce-ip ${IP}'
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-1/data:/data
      #- ./redis-cluster/nodes/node-1/log:/log
    ports:
      - 7001:7001
      - 17001:17001
    networks:
      redisNet:
        ipv4_address: 172.28.0.3
  redis-node-2:
    image: redis:5.0.9
    container_name: redis-node-2
    env_file: .env
    command: /bin/bash -c "redis-server /etc/redis/redis.conf --port 7002 --cluster-announce-ip ${IP}"
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-2/data:/data
      #- ./redis-cluster/nodes/node-2/log:/log
    ports:
      - 7002:7002
      - 17002:17002
    networks:
      redisNet:
        ipv4_address: 172.28.0.4
  redis-node-3:
    image: redis:5.0.9
    container_name: redis-node-3
    env_file: .env
    command: /bin/bash -c "redis-server /etc/redis/redis.conf --port 7003 --cluster-announce-ip ${IP}"
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-3/data:/data
      #- ./redis-cluster/nodes/node-3/log:/log
    ports:
      - 7003:7003
      - 17003:17003
    networks:
      redisNet:
        ipv4_address: 172.28.0.5
  redis-node-4:
    image: redis:5.0.9
    container_name: redis-node-4
    env_file: .env
    command: /bin/bash -c "redis-server /etc/redis/redis.conf --port 7004 --cluster-announce-ip ${IP}"
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-4/data:/data
      #- ./redis-cluster/nodes/node-4/log:/log
    ports:
      - 7004:7004
      - 17004:17004
    networks:
      redisNet:
        ipv4_address: 172.28.0.6
  redis-node-5:
    image: redis:5.0.9
    container_name: redis-node-5
    env_file: .env
    command: /bin/bash -c "redis-server /etc/redis/redis.conf --port 7005 --cluster-announce-ip ${IP}"
    volumes:
      - ./nodes/conf:/etc/redis
      #- ./redis-cluster/nodes/node-5/data:/data
      #- ./redis-cluster/nodes/node-5/log:/log
    ports:
      - 7005:7005
      - 17005:17005
    networks:
      redisNet:
        ipv4_address: 172.28.0.7
  redis-cluster-creator:
    image: redis:5.0.9
    entrypoint: [/bin/sh,-c,'echo "yes" | redis-cli --cluster create 172.28.0.2:7000 172.28.0.3:7001 172.28.0.4:7002 172.28.0.5:7003 172.28.0.6:7004 172.28.0.7:7005 --cluster-replicas 1']
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
    networks:
      redisNet:
        ipv4_address: 172.28.0.10
networks:
  redisNet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
                  gateway: 172.28.0.1
  default:
    external:
      name: external-connect
