version: "3.8"
services:
  redis:
    restart: always
    container_name: redis
    image: redis:5.0.13
    ports:
       - 6379:6379
    volumes:
       - ./redis/data:/data
       - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: /bin/bash -c 'redis-server /usr/local/etc/redis/redis.conf'
networks:
  default:
    external:
      name: external-connect
